CREATE TABLE IF NOT EXISTS car_name (id SERIAL PRIMARY KEY, name VARCHAR(30) NOT NULL, make_id INTEGER NOT NULL);
INSERT INTO car_name (name, make_id) VALUES ('integra', 1);
INSERT INTO car_name (name, make_id) VALUES ('rsx', 1);
INSERT INTO car_name (name, make_id) VALUES ('tsx', 1);
INSERT INTO car_name (name, make_id) VALUES ('tl', 1);
INSERT INTO car_name (name, make_id) VALUES ('nsx', 1);
INSERT INTO car_name (name, make_id) VALUES ('4c', 2);
INSERT INTO car_name (name, make_id) VALUES ('giulia', 2);
INSERT INTO car_name (name, make_id) VALUES ('vantage', 3);
INSERT INTO car_name (name, make_id) VALUES ('a4', 4);
INSERT INTO car_name (name, make_id) VALUES ('a5', 4);
INSERT INTO car_name (name, make_id) VALUES ('s4', 4);
INSERT INTO car_name (name, make_id) VALUES ('s5', 4);
INSERT INTO car_name (name, make_id) VALUES ('rs4', 4);
INSERT INTO car_name (name, make_id) VALUES ('rs5', 4);
INSERT INTO car_name (name, make_id) VALUES ('r8', 4);
INSERT INTO car_name (name, make_id) VALUES ('1 series', 5);
INSERT INTO car_name (name, make_id) VALUES ('2 series', 5);
INSERT INTO car_name (name, make_id) VALUES ('3 series', 5);
INSERT INTO car_name (name, make_id) VALUES ('4 series', 5);
INSERT INTO car_name (name, make_id) VALUES ('5 series', 5);
INSERT INTO car_name (name, make_id) VALUES ('8 series', 5);
INSERT INTO car_name (name, make_id) VALUES ('z3', 5);
INSERT INTO car_name (name, make_id) VALUES ('z4', 5);
INSERT INTO car_name (name, make_id) VALUES ('corvette', 6);
INSERT INTO car_name (name, make_id) VALUES ('camero', 6);
INSERT INTO car_name (name, make_id) VALUES ('challenger', 7);
INSERT INTO car_name (name, make_id) VALUES ('charger', 7);
INSERT INTO car_name (name, make_id) VALUES ('viper', 7);
INSERT INTO car_name (name, make_id) VALUES ('mustang', 9);
INSERT INTO car_name (name, make_id) VALUES ('focus', 9);
INSERT INTO car_name (name, make_id) VALUES ('civic', 10);
INSERT INTO car_name (name, make_id) VALUES ('accord', 10);
INSERT INTO car_name (name, make_id) VALUES ('s2000', 10);
INSERT INTO car_name (name, make_id) VALUES ('genesis', 11);
INSERT INTO car_name (name, make_id) VALUES ('veloster', 11);
INSERT INTO car_name (name, make_id) VALUES ('g35', 12);
INSERT INTO car_name (name, make_id) VALUES ('g37', 12);
INSERT INTO car_name (name, make_id) VALUES ('f type', 13);
INSERT INTO car_name (name, make_id) VALUES ('xe', 13);
INSERT INTO car_name (name, make_id) VALUES ('stinger', 14);
INSERT INTO car_name (name, make_id) VALUES ('is', 15);
INSERT INTO car_name (name, make_id) VALUES ('gs', 15);
INSERT INTO car_name (name, make_id) VALUES ('ct', 15);
INSERT INTO car_name (name, make_id) VALUES ('elise', 16);
INSERT INTO car_name (name, make_id) VALUES ('exige', 16);
INSERT INTO car_name (name, make_id) VALUES ('mx5', 17);
INSERT INTO car_name (name, make_id) VALUES ('rx7', 17);
INSERT INTO car_name (name, make_id) VALUES ('rx8', 17);
INSERT INTO car_name (name, make_id) VALUES ('mazda3', 17);
INSERT INTO car_name (name, make_id) VALUES ('c class', 18);
INSERT INTO car_name (name, make_id) VALUES ('s class', 18);
INSERT INTO car_name (name, make_id) VALUES ('slk', 18);
INSERT INTO car_name (name, make_id) VALUES ('cooper', 19);
INSERT INTO car_name (name, make_id) VALUES ('lancer', 20);
INSERT INTO car_name (name, make_id) VALUES ('3000gt', 20);
INSERT INTO car_name (name, make_id) VALUES ('eclipse', 20);
INSERT INTO car_name (name, make_id) VALUES ('240sx', 21);
INSERT INTO car_name (name, make_id) VALUES ('300zx', 21);
INSERT INTO car_name (name, make_id) VALUES ('350z', 21);
INSERT INTO car_name (name, make_id) VALUES ('370z', 21);
INSERT INTO car_name (name, make_id) VALUES ('240z', 21);
INSERT INTO car_name (name, make_id) VALUES ('gtr', 21);
INSERT INTO car_name (name, make_id) VALUES ('911', 22);
INSERT INTO car_name (name, make_id) VALUES ('cayman', 22);
INSERT INTO car_name (name, make_id) VALUES ('boxster', 22);
INSERT INTO car_name (name, make_id) VALUES ('frs', 23);
INSERT INTO car_name (name, make_id) VALUES ('tc', 23);
INSERT INTO car_name (name, make_id) VALUES ('xb', 23);
INSERT INTO car_name (name, make_id) VALUES ('impreza', 24);
INSERT INTO car_name (name, make_id) VALUES ('brz', 24);
INSERT INTO car_name (name, make_id) VALUES ('wrx', 24);
INSERT INTO car_name (name, make_id) VALUES ('model3', 25);
INSERT INTO car_name (name, make_id) VALUES ('toyota 86', 26);
INSERT INTO car_name (name, make_id) VALUES ('corolla', 26);
INSERT INTO car_name (name, make_id) VALUES ('supra', 26);
INSERT INTO car_name (name, make_id) VALUES ('celica', 26);
INSERT INTO car_name (name, make_id) VALUES ('mr2', 26);
INSERT INTO car_name (name, make_id) VALUES ('golf', 27);
INSERT INTO car_name (name, make_id) VALUES ('jetta', 27);